# Generated by Django 5.2.4 on 2025-08-07 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
        ('courses', '0004_delete_assignment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Assignment',
            new_name='Assessment',
        ),
    ]
